### ISSUE TITLE
Feature request: add option for second utility station

### ISSUE THREAD

**Issue by planktonek** [demipixel/factorio-generators#1]
Thanks for amazing work!

Could you add an option to add a second separate train station to unload things like repair packs, walls, turrets, ammo etc... of course to make it perfect there should be a belts/bots connection between ammo and turrets and an option to cover outpost in construction range of roboports (for outpost repair)

**Comment by demipixel** [comment]
Would it be better to have it come to the same train station, and it just unloads those things on the opposite side?

Covering an outpost in roboports will be difficult just because that requires finding the nooks and crannies where to place them and making sure you cover the entire thing.

**Comment by planktonek** [comment]
using 1 train stop for 2 different things is asking for the troubles. I usual build something like this http://imgur.com/a/dmFxV

if we talk about roboports we need to cover only walls part for the outpost for the repair but i will agree with you that it is tricky and don't needed so much as it is not a huge problem to manually put few roboports in the base ;)

**Comment by demipixel** [comment]
For now I'm going to close this, as I don't see us adding this in the near future (since there's a ton of things people want, for example on-site smelting an whatnot). However, a push was just made to support extra area next to the station (thanks to @Cyberboss ), so once that's implemented on Autotorio, it will be possible to easily add in your own station blueprint!
