### ISSUE TITLE
Feature Request: Small power pole option

### ISSUE THREAD

**Issue by kbickar** [demipixel/factorio-generators#27]
Small power poles cheaper and plentiful. They could replace medium power poles if there was an option

**Comment by demipixel** [comment]
By the time you have robots to use to build these outposts, I feel like steel is much easier to get than wood (plus, it's easier to automate medium electric poles than small electric poles). In addition, it would cause some additional issues with reach (e.g. They can't reach across 6 chests for each train wagon).

**Comment by kbickar** [comment]
Personally, I have billions of spare wood from clearing forest so my small pole factory has never run short.  For train loading I've usually replaced that with my own blueprint that has a power station:
![image](https://user-images.githubusercontent.com/3783553/35313445-630943e6-008e-11e8-9611-e73ed10b66ba.png)

**Comment by demipixel** [comment]
For now I don't really plan to implement this (since we would have to change distances calculated for power poles and such, and it's a very niche request. That being said, if you really want to use small power poles, you can always use Autotorio's replacer to convert medium electrics to smalls (just be aware that they might not reach in certain locations depending on your settings).
